# Generated by Django 5.1.7 on 2025-03-16 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_driver'),
        ('driver', '0002_driver_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='driver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_driver', to='driver.driver', verbose_name='Водитель'),
        ),
    ]
