# Generated by Django 5.1.7 on 2025-03-17 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='client',
        ),
    ]
