# Generated by Django 5.1.7 on 2025-03-17 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_user_client'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='client.client', verbose_name='Клиент'),
        ),
    ]
