# Generated by Django 5.1.7 on 2025-03-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_user_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('administrator', 'Администратор'), ('driver', 'Водитель'), ('client', 'Клиент'), ('guest', 'Гость')], default='guest', max_length=15),
        ),
    ]
