# Generated by Django 5.1.6 on 2025-02-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_driver_review_count_alter_driver_rating_driverreview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='year_of_manufacture',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
