# Generated by Django 5.1.6 on 2025-02-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_alter_vehicle_year_of_manufacture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='year_of_manufacture',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
