# Generated by Django 5.1.6 on 2025-02-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
        ('tracking', '0005_alter_vehicle_year_of_manufacture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='route',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='routes',
            field=models.ManyToManyField(blank=True, related_name='vehicles', to='map.route'),
        ),
    ]
