# Generated by Django 5.1.6 on 2025-02-27 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_remove_vehicle_route_vehicle_routes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='finish_time',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='routes',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='start_time',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
