# Generated by Django 5.1.6 on 2025-03-01 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_vehicle_capacity_vehicle_details_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('brand', models.CharField(default='Unknown', max_length=50)),
                ('max_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('year_of_manufacture', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='details_url',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='image',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='max_speed',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='year_of_manufacture',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='tracking.vehicletype'),
        ),
    ]
