# Generated by Django 5.1.6 on 2025-03-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0009_vehicletype_remove_vehicle_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_types/'),
        ),
    ]
