# Generated by Django 5.1.7 on 2025-03-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/client/'),
        ),
    ]
