# Generated by Django 5.1.7 on 2025-03-16 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_alter_driver_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
