# Generated by Django 5.1.7 on 2025-03-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_driver_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverreview',
            old_name='user',
            new_name='client',
        ),
        migrations.AddField(
            model_name='driver',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='driver_avatars/'),
        ),
    ]
